### PR TITLE
Add Elasticsearch Liveness

### PR DESCRIPTION
**Pull request by poumup**

### CODE REVIEW

**Comment by unaizorrilla** [comment]
Hi @poumup  

Some tests are failing on appveyor, can you check and fix these? 
https://ci.appveyor.com/project/Xabaril/beatpulse/builds/20217341

**Comment by poumup** [comment]
If all is ok. could you please add the provider for the next release

**Comment by unaizorrilla** [comment]
Hi poumul!

Merged and created new tag, when the release build finish the new package should be created and pushed to Nuget.

Could you create this provider also for the new HealthCheck system for ASP.NET Core on the https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/ repo?  Is the same but using new ASP.NET Core 2.2 HealthChecks abstractions!!!

**Comment by unaizorrilla** [comment]
If is not interesting for you ( creating this provider for the new HealthCheck ) I can do that, please, let me know!

Unai

**Pull request merged**
