### PR TITLE
Multiple disposals of DBContext causes memory leaks

### PR DESCRIPTION
**Pull request by szogun1987**
Datacontext was disposed couple of times.

1. it was disposed by every dependency that uses it - it shouldn't be because it is injected into them not created by them.
2. it was disposed directly by MiddleWare by using statement
3. it was disposed by scope disposal

In some cases DbContext was disposed before liveness runner was, then runner used it and usage was passed to sqlite driver below. driver itself resurects resources it used in this case. Because dbContext was already disposed it didn't redispose driver, so resources allocated by it left in memory.
I have also added usage of cancellationToken and upgraded dependencies.

### CODE REVIEW

**Comment by szogun1987** [comment]
BTW Some commits are already merged, IDK why they are on list.

**Comment by szogun1987** [comment]
Done

**Comment by szogun1987** [comment]
I figured that DbContext throws exception if it is disposed second time. I have to investigate problem deeper.

**Comment by szogun1987** [comment]
OK. My changes doesn't improve memory usage, but still seems to be worth to merge. I would extend Cancellation handling a little bit also.

**Comment by unaizorrilla** [comment]
Merged, sorry for delay on approval this PR

**Comment by szogun1987** [comment]
For some reason new version of library was not released, can you check why?

**Comment by unaizorrilla** [comment]
Published a new tag, sorry @szogun1987

**Comment by szogun1987** [comment]
Thanks

**Pull request merged**
