### PR TITLE
Add EventstoreLiveness Provider

### PR DESCRIPTION
**Pull request by poumup**

### CODE REVIEW

**Comment by unaizorrilla** [comment]
Hi @poumup 

Sounds good, could you create this PR also for https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/ ? As you known, with ASP.NET Core 2.2 a new HealthChecks system is released out of box and Xabaril team are migrating all health checks into this new project.
For me is very interesting to have this health checks also on new project, sound well for you?

Unai

**Comment by poumup** [comment]
of course.

**Comment by poumup** [comment]
I had change the readme and test are failed. Strange no ?

**Comment by unaizorrilla** [comment]
let me see this afternoon!

**Comment by unaizorrilla** [comment]
Hi @poumup ,

Merged and added also the packages on ps1 (also missing entry for elasitic search). 

Could you add also this liveness into the https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/ repo? This is the repo with HealthChecks for the new abstractions on ASP.NET Core 2.2

thanks
Unai

**Comment by poumup** [comment]
@unaizorrilla the PR for the new abstractions on ASP.NET Core 2.2 is comming

**Comment by unaizorrilla** [comment]
Thanks

**Pull request merged**
